### ISSUE TITLE
Adding tags and URL

### ISSUE THREAD

**Issue by eliasdabbas** [PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash#2]
@utkarsha-Packt 

Can we please have the app's URL at the top of the repo as the main link? 

https://povertydata.org/

Also, it would be great if we add the following topics to the repo:

python
plotly
dashboard
data-visualization
plotly-dash
frontend
analytics

Thanks a lot!

**Comment by eliasdabbas** [comment]
@ManikandanKurup-Packt 

Just curious if there is any update on this? 

Thanks a lot.

**Comment by ManikandanKurup-Packt** [comment]
Hi @eliasdabbas 

Apologies for the delay. I missed the e-mail notification for this issue. I have updated the About section of the repo with the details that you mentioned. Let me know if it's good or if you want to add anything more. :)

Best regards.

**Comment by eliasdabbas** [comment]
Looks good. Thanks a lot @ManikandanKurup-Packt !
