### ISSUE TITLE
How to redeem hosting credits at Linode?

### ISSUE THREAD

**Issue by EricThomson** [PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash#3]
On the github page it says:

> You also get a $100 hosting credit from Linode (to be consumed within 60 days of creating your account), so you can test it on an actual server and share it with the world.

How do we redeem this?

**Comment by eliasdabbas** [comment]
You can redeem it through the book's special page: 

https://linode.com/dashbook 

Just keep in mind that you can use the credits for 60 days, and then they expire, so make sure you register and start using them when you are ready to deploy. 

Good luck!

**Comment by EricThomson** [comment]
Great thanks!
