### ISSUE TITLE
pip install - ERROR: Failed building wheel for numpy

### ISSUE THREAD

**Issue by BenZhen14** [PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash#5]
Hello, i'm on page 5 and attempted to install the requirements.txt but I am receiving an unusual error. (See error.txt below).
[error.txt](https://github.com/PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash/files/10877973/error.txt)

I can install the numpy version 1.24.2 but the requirements.txt calls for 1.20.1. I played around with this a bit and can't install 1.20.1 and I altered the requirements.txt file to have version 1.24.2 with no luck. I also removed/commented the line out but it still errors out.

FWIW I'm running on an Apple M1 MacBook. I don't know if there's some sort of incompatibility issue here.

python = 3.9.6
pip = 23.0.1
wheel = 0.38.4

**Comment by eliasdabbas** [comment]
@BenZhen14 Thanks a lot for reporting.

I'm not sure why this is happening. I just tested on a Mac, with Python v3.9.2, and installed the packages with no problem. 

Can you please check your virtual environment? Or maybe start a new one from scratch?

**Comment by BenZhen14** [comment]
@eliasdabbas Out of curiosity, are you using an Intel or ARM based Mac? I only ask because I have two Apple Silicon Macs and it failed on both.

I started from scratch on both Macs but unfortuantely, I ran into the same issue.

**Comment by eliasdabbas** [comment]
I'm using an Intel-based Mac. I doubt this would be the reason, but I don't really know.

Can you please share the exact steps you took (including the virtual environment), so I can double check?

**Comment by BenZhen14** [comment]
It's just strange. I used my old 2015 MacBook Pro with an Intel chip and everything installed successfully using Python version 3.9.1 and pip version 20.2.3.

Please see the attachment for the detailed steps on the system having issues.
[error.txt](https://github.com/PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash/files/10899644/error.txt)

**Comment by eliasdabbas** [comment]
This is indeed really strange...
Thanks again for letting me know, and I'll check to see what might be the solution for this. 

Hope you enjoy the book!
